server:
  port: 8082
  context-path: /cagister

spring:
  datasource: # Database properties
    url: jdbc:h2:./.tmp/cagisterdb
    username: sa
    password:
#    data: classpath:/load-test-data.sql
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: validate

security:
  user:
    name: apiuser
    password: password

flyway: # Flyway properties
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}