/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '6/11/16 11:08 PM' with Gradle 2.9
 *
 * @author sqlin, @date 6/11/16 11:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
